version: "3"
services:
  usertest:
    image: prodotto:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prodotto
    restart: always
    ports:
      - 8080:8080
    networks:
      - prodotto
networks:
  prodotto:
    external: true